version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: erp
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_server
    command: redis-server --requirepass admin
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  redis_data:
  mongo_data:
